### ISSUE TITLE
Collection does not appear to support FQCN

### ISSUE THREAD

**Issue by nickrusso42518** [nokia/ansible-networking-collections#16]
There are generally two ways to use collections in Ansible.

You can include them at the play level, which appears to be required by Nokia. The following snippet is from the Nokia docs:
```
  collections:
  - nokia.sros

  tasks:
  - name: get system information
    cli_command:
      command: show system information
    register: output1
```

Or, you can use the FQCN approach:

```
  tasks:
  - name: get system information
    nokia.sros.cli_command:
      command: show system information
    register: output1
```

The latter approach does not appear to be supported. It is not clear whether this is an Ansible issue or a Nokia issue. I personally believe it to be a Nokia issue because the `modules/` directory does not contain `cli_command`, which appears to be dynamically (?) made available only after the collection is imported at the play level. In this way, it cannot work with the FQCN method, which also explains why it does not appear in the "content" tab of the galaxy documentation.

Note that Ansible recommends FQCNs: "We recommend you start using the fully-qualified collection name (FQCN) in your playbooks as the explicit and authoritative indicator of which collection to use ..."
