### ISSUE TITLE
Handling /file portion of the CLI possible?

### ISSUE THREAD

**Issue by coxoperationsengineer** [nokia/ansible-networking-collections#18]
@wisotzky 

I might be missing the obvious here, but is there a way with the nokia.sros/nokia.sros.light plugin's to browse into the file tree?  I have tried sending something like this but I suspect it is wanting to see the response of each individual command and never seeing std_out, so it just hangs until command timeout is triggered.

```"/file\ncd cf3:\\images\\TiMOS-B-16.0.R10\ndir\n"```

**Comment by wisotzky** [comment]
Hi @coxoperationsengineer,

Please check the Ansible documentation. To my understanding, the Ansible `cli_command` module only supports a single command. That implies one need to issue multiple `cli_command` statements. The solution would not split the command string at every newline. While you may think, this should not really matter, you are basically confusing the command prompt detection.

I would suggest to try the following:

```
- name: enter directory
  ansible.netcommon.cli_command:
    command: /file cd cf3:\\images\\TiMOS-B-16.0.R10
- name: list directory
  ansible.netcommon.cli_command:
    command: /file dir
```

Alternatively, Nokia SR OS supports to run everything as a single command:
```
- name: get directory
  ansible.netcommon.cli_command:
    command: /file dir cf3:\\images\\TiMOS-B-16.0.R10
```

Have fun!
